language: node_js
node_js:
  - stable

# Use a simple Trusty Tahr server for testing.
os: linux
dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update
  - sudo apt-get install -y --force-yes nginx-extras

install:
  # Lint, build and test UnSHACLed.
  - pushd UnSHACLed; npm install && xvfb-run gulp; popd
  # Patch the server configuration and install it.
  - ./patch-server.sh $(pwd)/UnSHACLed 8080
  - sudo ./install-server.sh default

script:
  # (Re)load nginx.
  - sudo nginx -c /etc/nginx/nginx.conf
  # For some reason, nginx hosted in a Travis container
  # always replies with 404. This works fine on our server,
  # though. So maybe it's just a virtualization quirk.
  # - ls -l /etc/nginx/sites-available
  # - ls -l /etc/nginx/sites-enabled
  # - cat /etc/nginx/sites-available/default
  # Try to download a bunch of files.
  # - wget -O - http://localhost:8080/index.html
  # - wget http://localhost:8080/dist/unshacled.min.js
