language: node_js
node_js:
  - stable

# Use a simple Trusty Tahr server to deploy.
os: linux
dist: trusty
sudo: required

addons:
  apt:
    packages:
      - nginx

install:
  # Lint, build and test UnSHACLed.
  - pushd UnSHACLed; npm install && xvfb-run gulp; popd
  # Patch the server configuration and install it.
  - ./patch-server.sh $(pwd)/UnSHACLed 8080
  - sudo ./install-server.sh

script:
  # (Re)load nginx.
  - sudo nginx -c /etc/nginx/nginx.conf
  - ls -l /etc/nginx/sites-available
  - ls -l /etc/nginx/sites-enabled
  - cat /etc/nginx/sites-available/default
  # Try to download a bunch of files.
  - wget -O - http://localhost:8080/index.html
  - wget http://localhost:8080/dist/unshacled.min.js
